name: CI

on: push

env:
  APP_NAME: my-app

jobs:
   test-secrets:
      runs-on: ubuntu-latest
      steps:
        - name: test secret
          env:
           secret: ${{ secrets.PASSWORD }}
          run: echo "The secret exists!"


